### ISSUE TITLE
Nim version is really old

### ISSUE THREAD

**Issue by apahl** [samuell/gccontent-benchmark#18]
Hi Samuel, 
thanks for starting this mini-benchmark.
The Nim version you are using is really old, it is maybe worth trying a more recent one (current is 1.4.2) (and applying the `d:danger` option)?

Kind regards,
Axel

**Comment by ghost** [comment]
Yeah, the current Nim options are not the best - usually you'd use `-d:release` to compile a release build with runtime checks enabled, and `-d:danger` to do the same, but without runtime checks (fastest option generally). And 0.17.2 Nim version was released in September 2017 (which is very old for Nim which is still a quite fast-moving target)

**Comment by samuell** [comment]
Many thanks @apahl and @Yardanico ! Having a look at updating this later today! :+1:
